language: python
sudo: false
python:
- 2.7
- 3.5
script:
- pip install coveralls
- python setup.py develop
- coverage run setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: Kaniabi
  on:
    tags: true
    repository: zerotk/easyfs
  password:
    secure: zu+g6ueFF1D0yNyHz7e0xZVJUWnp8tZpVo4/z0ez9pNRCHGdv5/QFLzuACyjDX2/qbisJOXmXzMPqJQ8svcMlGwPujzI6Dhf5R+Vg1TBjHNgmZbeeMITRd6qqxtf2zFo9LkqQ0b71zN7+oS3F2DiODZQHHRdYfdZr9Eu473sc5Vqk33Hta6+krk1cdIe7FO7Wkbs1sQXDgrksENbIwdvjujgj89vvOocm8l/GbmnuPV4w4XIozd+961TSL+qGzcK4/oNyTpS3enbLsD/8JyP/oaCcoPaxQo6QbKNRbOnrFWjcmXSG3v94EHtHHFpU2rSN44aF1hx1VeH8IFoe7267ZYjGnP8YPYhgwmuovrHhg2iROk+Btw59eWd3wVZeMh0uM3d1aAzovH0vvHoLddcdk8V6at8PlRri0Bsxs1CEwqVpspA3bm6u9RaqABsRfoj8DXz+IZTSlB2t00pbKh6eEpK9W+zjjq4I+PAAzthnv0QDYC1cXnSczCPUY3JE90C17OkElyI737/CdHTKzh8OybusWrD8c8ro6e/ge7AQYfgubXUO1CxeCR53Gb6L2JeqXxg1HSu/SQ60ZdrkU/FcnLHIg1qNF5NGbTr8+BxwC/CDKlQBfz8ecwDgajWx0DltUPpEEi/QNF4D+uSWsqijyVIRvHKEx6TwkbmN90t52A=
