language: python
sudo: false
python:
- 2.7
- 3.5
script:
- pip install coveralls
- python setup.py develop
- coverage run setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: Kaniabi
  on:
    tags: true
    repository: zerotk/easyfs
  password:
    secure: 7jVxJlC0dCgtfgOcfUq+nPCD2HnJLzslRRG+2pJ1noHK6g+kl7Mv/xtttw31JZkwBLC2ZnoG3JQ8WBxuhd1lKZ2zrTB2yvgNjVAxjSLwBqqjPt+raGIc8jD9rXt3lM9umokGUjjaNdtdX5EjNcL0dtIA3+Rt3J5FKhIegzvHwTLNj/GuzPn0eMRhcbb0LtCjE5hsiswdOqPF1TLNAp7n5hqoFhD/RqHZhJzsOh2e8sHN0DfIi/XiR4Hbyj5EXPZv1Hp5pafbeW1gvrL0jvF4Acedi321nspyJYzgfGYZoxWktDkhtIUrr9WD9E3nqa57qK8q1H7CEGmVesJem/rrBBwp1iv9Y416cWTX9vkvibQLwraBX54jjk7HHiTEQDfnYbeMJ+YbLOPmDYmeNKTb0OYlkylGpP3szoopgrKp5RJa+Sk3QKzAwlgQLlZg9s+DNp2c9f0HVxg7VCsIpltXodF978GfXuJoumJX1q7nGfkpObwEaX1uRgGMNq5qYojN6gQ32VMoLWinneoUgok8hTdh30ZmtUcOtYdKBMe+JtgS+rVNAEekHcsk94hFdUFJlUGm3ZlIMeR7s6ZSxL+lTBYNWFF9bNzpVy5CvJ9xze92fUmNMaVzW5DZk8RQbKcxa7PdwwA8xb4cILAIwpfjnwONCbGMh4wpoIeBjNzpCoE=
