build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe -m pip install --disable-pip-version-check --user --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install coveralls"

test_script:
  - "%PYTHON%\\python.exe setup.py develop"
  - "%PYTHON%\\python.exe -m coverage run setup.py test"

#after_test:
#  # If tests are successful, create binary packages for the project.
#  - "%CMD_IN_ENV% python setup.py bdist_wheel"
#  - "%CMD_IN_ENV% python setup.py bdist_wininst"
#  - "%CMD_IN_ENV% python setup.py bdist_msi"
#  - ps: "ls dist"

#artifacts:
#  # Archive the generated packages in the ci.appveyor.com build report.
#  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
